CREATE TABLE IF NOT EXISTS orders (
    ID CHAR(36) NOT NULL PRIMARY KEY,
    USER_ID CHAR(36) NOT NULL,
    PAYMENT_TYPE CHAR(36) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items (
    ID CHAR(36) NOT NULL PRIMARY KEY,
    PRODUCT_ID CHAR(36) NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 1,
    PRICE DECIMAL(12, 2) NOT NULL
);
