CREATE TABLE IF NOT EXISTS carts (
    ID CHAR(36) NOT NULL PRIMARY KEY,
    SESSION_ID CHAR(36) NOT NULL,
    PRODUCT_ID CHAR(36) NOT NULL,
    QUANTITY INT DEFAULT 1,
    PRICE DECIMAL(12,2) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
